-- AlterTable
ALTER TABLE "cards" ALTER COLUMN "oracle_id" DROP NOT NULL,
ALTER COLUMN "type_line" DROP NOT NULL,
ALTER COLUMN "image_url" DROP NOT NULL,
ALTER COLUMN "oracle_text" DROP NOT NULL,
ALTER COLUMN "mana_cost" DROP NOT NULL,
ALTER COLUMN "cmc" SET DEFAULT 0;
